- Retabbed source.

diff --git a/packaging/firewall-start b/packaging/firewall-start
--- a/packaging/firewall-start
+++ b/packaging/firewall-start
@@ -69,10 +69,10 @@ FW_LOCKFILE="/var/run/firewall.pid"
 # Pretend mode?
 PRETEND=0
 for (( i=0; i<$#; i++)); do
-	if [ ${BASH_ARGV[$i]} == "-p" ]; then
-		PRETEND=1
-		break
-	fi
+    if [ ${BASH_ARGV[$i]} == "-p" ]; then
+        PRETEND=1
+        break
+    fi
 done
 
 # TODO: detect installer environment properly
@@ -105,77 +105,77 @@ export GATEWAYDEV
 # Pull in syswatch interface list
 source $FW_CONF
 if [ -f "$SYSWATCH_STATE" ]; then
-	source $SYSWATCH_STATE
+    source $SYSWATCH_STATE
 else
-	SYSWATCH_WANIF="$EXTIF"
+    SYSWATCH_WANIF="$EXTIF"
 fi
 
 # TODO: A quick hack to determine proxy user authentication mode
 USERAUTH=`grep "http_access.*webconfig_lan.*password" /etc/squid/squid.conf 2>/dev/null`
 if [ -n "$USERAUTH" ]; then
-	SQUID_USER_AUTHENTICATION="on"
+    SQUID_USER_AUTHENTICATION="on"
 else
-	SQUID_USER_AUTHENTICATION="off"
+    SQUID_USER_AUTHENTICATION="off"
 fi
 
 # Export firewall configuration
 export MODE EXTIF LANIF HOTIF DMZIF WIFIF BANDWIDTH_QOS BANDWIDTH_UPSTREAM \
-	BANDWIDTH_UPSTREAM_BURST BANDWIDTH_UPSTREAM_CBURST BANDWIDTH_DOWNSTREAM \
-	BANDWIDTH_DOWNSTREAM_BURST BANDWIDTH_DOWNSTREAM_CBURST \
+    BANDWIDTH_UPSTREAM_BURST BANDWIDTH_UPSTREAM_CBURST BANDWIDTH_DOWNSTREAM \
+    BANDWIDTH_DOWNSTREAM_BURST BANDWIDTH_DOWNSTREAM_CBURST \
     QOS_ENABLE QOS_ENGINE QOS_UPSTREAM QOS_DOWNSTREAM \
     QOS_PRIOMARK4 QOS_PRIOMARK6 QOS_PRIOMARK_CUSTOM \
     SQUID_TRANSPARENT SQUID_USER_AUTHENTICATION IPSEC_SERVER PPTP_SERVER \
-	PPTP_PASSTHROUGH_FORCE ONE_TO_ONE_NAT_MODE LANNET MULTIPATH \
-	MULTIPATH_WEIGHTS RULES MULTIPATH_SKIP_DOWN_WANIF FW_LOG_DROPS \
-	SYSWATCH_WANIF EGRESS_FILTERING PROTOCOL_FILTERING
+    PPTP_PASSTHROUGH_FORCE ONE_TO_ONE_NAT_MODE LANNET MULTIPATH \
+    MULTIPATH_WEIGHTS RULES MULTIPATH_SKIP_DOWN_WANIF FW_LOG_DROPS \
+    SYSWATCH_WANIF EGRESS_FILTERING PROTOCOL_FILTERING
 
 # Panic mode rules.  If the firewall fails, then we run these rules to ensure
 # we have something sane configured.
 RunPanicRules() {
-	if [ $PRETEND -eq 1 ]; then return; fi
+    if [ $PRETEND -eq 1 ]; then return; fi
 
-	echo "Running firewall panic mode..."
-	/usr/bin/logger -p $FW_FACILITY.error -t firewall "Running firewall panic mode..."
+    echo "Running firewall panic mode..."
+    /usr/bin/logger -p $FW_FACILITY.error -t firewall "Running firewall panic mode..."
 
-	for TABLE in filter nat mangle; do
-		$IPTABLES -t $TABLE -F  # Flush all previous rules.
-		$IPTABLES -t $TABLE -X  # Delete user-defined chains.
-	done
+    for TABLE in filter nat mangle; do
+        $IPTABLES -t $TABLE -F  # Flush all previous rules.
+        $IPTABLES -t $TABLE -X  # Delete user-defined chains.
+    done
 
-	$IPTABLES -P INPUT DROP
-	$IPTABLES -P OUTPUT DROP
-	$IPTABLES -P FORWARD DROP
+    $IPTABLES -P INPUT DROP
+    $IPTABLES -P OUTPUT DROP
+    $IPTABLES -P FORWARD DROP
 
-	# Allow ping for diagnostics
-	$IPTABLES -A INPUT -p icmp -j $FW_ACCEPT
-	$IPTABLES -A OUTPUT -p icmp -j $FW_ACCEPT
+    # Allow ping for diagnostics
+    $IPTABLES -A INPUT -p icmp -j $FW_ACCEPT
+    $IPTABLES -A OUTPUT -p icmp -j $FW_ACCEPT
 
-	# Open 81 and 22
-	$IPTABLES -I INPUT -p tcp --dport 81 -j $FW_ACCEPT
-	$IPTABLES -I OUTPUT -p tcp --sport 81 -j $FW_ACCEPT
-	$IPTABLES -I INPUT -p tcp --dport 22 -j $FW_ACCEPT
-	$IPTABLES -I OUTPUT -p tcp --sport 22 -j $FW_ACCEPT
+    # Open 81 and 22
+    $IPTABLES -I INPUT -p tcp --dport 81 -j $FW_ACCEPT
+    $IPTABLES -I OUTPUT -p tcp --sport 81 -j $FW_ACCEPT
+    $IPTABLES -I INPUT -p tcp --dport 22 -j $FW_ACCEPT
+    $IPTABLES -I OUTPUT -p tcp --sport 22 -j $FW_ACCEPT
 
-	# Allow DNS requests
-	$IPTABLES -A INPUT -p udp --sport domain -j $FW_ACCEPT
-	$IPTABLES -A OUTPUT -p udp --dport domain -j $FW_ACCEPT
-	$IPTABLES -A INPUT -p tcp --sport domain -j $FW_ACCEPT
-	$IPTABLES -A OUTPUT -p tcp --dport domain -j $FW_ACCEPT
+    # Allow DNS requests
+    $IPTABLES -A INPUT -p udp --sport domain -j $FW_ACCEPT
+    $IPTABLES -A OUTPUT -p udp --dport domain -j $FW_ACCEPT
+    $IPTABLES -A INPUT -p tcp --sport domain -j $FW_ACCEPT
+    $IPTABLES -A OUTPUT -p tcp --dport domain -j $FW_ACCEPT
 
-	# Allow DHCP to startup
-	$IPTABLES -A INPUT -p udp --dport bootpc --sport bootps -j $FW_ACCEPT
-	$IPTABLES -A INPUT -p tcp --dport bootpc --sport bootps -j $FW_ACCEPT
-	$IPTABLES -A OUTPUT -p tcp --sport bootpc --dport bootps -j $FW_ACCEPT
-	$IPTABLES -A OUTPUT -p udp --sport bootpc --dport bootps -j $FW_ACCEPT
+    # Allow DHCP to startup
+    $IPTABLES -A INPUT -p udp --dport bootpc --sport bootps -j $FW_ACCEPT
+    $IPTABLES -A INPUT -p tcp --dport bootpc --sport bootps -j $FW_ACCEPT
+    $IPTABLES -A OUTPUT -p tcp --sport bootpc --dport bootps -j $FW_ACCEPT
+    $IPTABLES -A OUTPUT -p udp --sport bootpc --dport bootps -j $FW_ACCEPT
 
-	# Allow high ports
-	$IPTABLES -A OUTPUT -p tcp --sport 1024:65535 -j $FW_ACCEPT
-	$IPTABLES -A INPUT -p tcp --dport 1024:65535 \
-		-m state --state ESTABLISHED,RELATED -j $FW_ACCEPT
+    # Allow high ports
+    $IPTABLES -A OUTPUT -p tcp --sport 1024:65535 -j $FW_ACCEPT
+    $IPTABLES -A INPUT -p tcp --dport 1024:65535 \
+        -m state --state ESTABLISHED,RELATED -j $FW_ACCEPT
 
-	# Allow everything on the loopback
-	$IPTABLES -A INPUT -i lo -j $FW_ACCEPT
-	$IPTABLES -A OUTPUT -o lo -j $FW_ACCEPT
+    # Allow everything on the loopback
+    $IPTABLES -A INPUT -i lo -j $FW_ACCEPT
+    $IPTABLES -A OUTPUT -o lo -j $FW_ACCEPT
 }
 
 # lua barfs if this is not loaded
@@ -184,26 +184,26 @@ modprobe ip_tables
 # Run Lua application
 RC=0
 if (set -o noclobber; echo "$$" > "$FW_LOCKFILE") 2> /dev/null; then
-	trap 'rm -f "$FW_LOCKFILE"; exit $RC' INT TERM EXIT
+    trap 'rm -f "$FW_LOCKFILE"; exit $RC' INT TERM EXIT
 
-	if ($APP_FW -s $@ $APP_LUA); then
-		rm -f "$FW_LOCKFILE"
+    if ($APP_FW -s $@ $APP_LUA); then
+        rm -f "$FW_LOCKFILE"
         if [ x$MULTIPATH_SYNC == "xtrue" ]; then
             exit $RC
         fi
 
-		# Run Custom/ad-hoc rules
-		# XXX: This used to be run before anything else, but because we are now
-		# queueing rules until iptc_commit(), it makes no sense to run an
-		# external script because whatever it does will be cleared by
-		# iptc_commit().  Using the Advanced firewall rule creator in webconfig
-		# will allow custom rules to be run before others.  Ad-hoc rules should
-		# use -I to insert rules ahead of others if need be.
-		if [ -e $FW_CUSTOM ]; then
-			source $FW_CUSTOM || RC=1
-			/usr/bin/logger -p local6.notice -t firewall "Running $FW_CUSTOM"
-			/usr/bin/logger -p local6.notice -t firewall -f $FW_CUSTOM
-		fi
+        # Run Custom/ad-hoc rules
+        # XXX: This used to be run before anything else, but because we are now
+        # queueing rules until iptc_commit(), it makes no sense to run an
+        # external script because whatever it does will be cleared by
+        # iptc_commit().  Using the Advanced firewall rule creator in webconfig
+        # will allow custom rules to be run before others.  Ad-hoc rules should
+        # use -I to insert rules ahead of others if need be.
+        if [ -e $FW_CUSTOM ]; then
+            source $FW_CUSTOM || RC=1
+            /usr/bin/logger -p local6.notice -t firewall "Running $FW_CUSTOM"
+            /usr/bin/logger -p local6.notice -t firewall -f $FW_CUSTOM
+        fi
 
         if [ -e $FW_ADHOC ]; then
             source $FW_ADHOC || RC=1
@@ -216,18 +216,18 @@ if (set -o noclobber; echo "$$" > "$FW_LOCKFILE") 2> /dev/null; then
             /usr/bin/logger -p local6.notice -t firewall "Running $FW_APP"
             /usr/bin/logger -p local6.notice -t firewall -f $FW_APP
         done
-	else
-		RC=1
-		rm -f "$FW_LOCKFILE"
+    else
+        RC=1
+        rm -f "$FW_LOCKFILE"
         if [ x$MULTIPATH_SYNC != "xtrue" ]; then
-		    RunPanicRules
+            RunPanicRules
         fi
-	fi
+    fi
 else
-	echo "Failed to acquire lock: $FW_LOCKFILE (held by $(cat $FW_LOCKFILE))"
-	exit 1
+    echo "Failed to acquire lock: $FW_LOCKFILE (held by $(cat $FW_LOCKFILE))"
+    exit 1
 fi 
 
 exit $RC
 
-# vim: ts=4 syntax=sh
+# vi: syntax=sh expandtab shiftwidth=4 softtabstop=4 tabstop=4
